### ISSUE TITLE
Utility descriptions

### ISSUE THREAD

**Issue by husseinalhammad** [bly-th/css-website#3]
I think it would be helpful to have more descriptive definitions of each utility in the docs. At the moment all utilities are described as:

> Our {name} utility is constructed as follows:

**Comment by ryangittings** [comment]
Completely agree. Plans are in place to upgrade the documentation, purpose and examples of utilities.

**Comment by ryangittings** [comment]
Now drafted, https://github.com/bly-th/css-website/pull/4 / https://deploy-preview-4--blythcss.netlify.app/

It does need a refining, but good to get something drafted on this as it's quite an important part of Blyth! See what you think.

**Comment by husseinalhammad** [comment]
Thanks, @ryangittings! This is very helpful. 

## Auto Grid
I think the long paragraph of the `--auto-grid-min` explanation under the purpose section is a little hard to read. Perhaps it would be easier to read if `--auto-grid-method` and `--auto-grid-min` were `h3`s so the explanation of each can take as many paragraphs as needed.

**Comment by ryangittings** [comment]
Hopefully improved with https://github.com/bly-th/css-website/commit/6d7a64c7615863075ee918c858abe7d3e41c9810

**Comment by husseinalhammad** [comment]
Looks great! Thank you
