### ISSUE TITLE
Design Tokens: property and items

### ISSUE THREAD

**Issue by husseinalhammad** [bly-th/css-website#6]
The [Design Tokens](https://blythcss.dev/docs/tokens/) page links to the [property page](https://blythcss.dev/docs/tokens/property/), but the page doesn't exist at the moment. 

It would be great if the `property` and `items` properties are documented like `responsive` and `variable`:

```
text: {
  items: theme.sizeScale,
  responsive: true,
  property: 'font-size',
},
```

**Comment by ryangittings** [comment]
Good spot, fixed and added! https://github.com/bly-th/css-website/commit/6a10b87ed0c248e53d45926a2140ef035a818ff0

**Comment by husseinalhammad** [comment]
Perfect! You work fast 🚀
